# Generated by Django 5.1.7 on 2025-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('SGT', 'Sergent'), ('SCH', 'Sous-chef'), ('ADJ', 'Adjudant'), ('ADC', 'Adjudant-chef'), ('SLT', 'Sous-lieutenant'), ('LT', 'Lieutenant'), ('CNE', 'Capitaine'), ('CDT', 'Commandant'), ('LT-COL', 'Lieutenant-colonel'), ('COL', 'Colonel')], default='SGT', max_length=10, verbose_name='Grade'),
        ),
    ]
