# Generated by Django 5.1.7 on 2025-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NEZ', 'NEZ'), ('PRINCIPALE', 'PRINCIPALE')], max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=50)),
                ('nombre_de_deposes', models.IntegerField()),
                ('dernier_ndi', models.IntegerField()),
                ('prochain_ndi', models.IntegerField()),
                ('obs', models.TextField()),
            ],
        ),
    ]
