# Generated by Django 5.1.7 on 2025-04-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jante',
            name='dernier_ndi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jante',
            name='nombre_de_deposes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jante',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jante',
            name='prochain_ndi',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
